---
- name: configure pbench-fio
  blockinfile:
    path: /opt/pbench-agent/config/pbench-agent.cfg
    insertbefore: "[config]"
    content: |
      [pbench-fio]
      version = 3.3
      histogram_interval_msec = 10000

- name: register tools
  shell: pbench-register-tool-set
  # ignore errors because the turobstat tool cannot be registered in a VM
  ignore_errors: yes

- name: run a quick pbench test
  shell: pbench-user-benchmark -C pbench_test_{{ ansible_date_time.date }} -- sleep 10

- name: test pbench-copy-results
  shell: pbench-copy-results
  # many node deployments may have errors
  ignore_errors: yes

- name: clean up pbench
  shell: pbench-clear-tools ; pbench-clear-results
